# Generated by Django 5.2.12 on 2026-03-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftsAndProjects', '0002_remove_project_ai_score_alter_project_desc_and_more'),
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='draftsAndProjects.project'),
        ),
    ]
