# Generated by Django 6.0.3 on 2026-03-27 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldPic', models.ImageField(upload_to='waste/')),
                ('newPic', models.ImageField(blank=True, null=True, upload_to='result/')),
                ('desc', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('finished', 'Finished')], default='draft', max_length=10)),
                ('recordedTime', models.DateTimeField(auto_now_add=True)),
                ('ai_score', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
