# Generated by Django 5.2.12 on 2026-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftsAndProjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ai_score',
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
